CSBlog/Controllers/CommentController.cs
using CSBlog.Core.Repository;
using Microsoft.AspNetCore.Mvc;

namespace CSBlog.Controllers;

public class CommentController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
  // private readonly ApplicationDbContext _context;

  public CommentController(IUnitOfWork unitOfWork)
  {
    _unitOfWork = unitOfWork;
  }

  // GET
  public IActionResult GetArticleComments(string articleId)
  {
    var comments = _unitOfWork.Comment.GetAll().Where(t => t.ArticleId == articleId);
    
    return Json(comments);
  }
}

CSBlog/Controllers/RoleController.cs
using CSBlog.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CSBlog.Controllers;

public class RoleController : Controller
{

  [Authorize]
  public IActionResult Index()
  {
    return View();
  }
  
  [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Moderator}")]
  public IActionResult Moderator()
  {
    return View();
  }


  [Authorize(Policy = Constants.Policies.RequireAdmin)]
  public IActionResult Admin()
  {
    return View();
  }
}

CSBlog/Controllers/TagController.cs
using CSBlog.Core.Repository;
using CSBlog.Core.ViewModels.Blog;
using CSBlog.Data;
using CSBlog.Models.Blog;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Constants = CSBlog.Core.Constants;

namespace CSBlog.Controllers;

[Authorize(Policy = Constants.Policies.RequireModerator)]
public class TagController : Controller
{
  private readonly IUnitOfWork _unitOfWork;
  private readonly ApplicationDbContext _context;

  public TagController(IUnitOfWork unitOfWork, ApplicationDbContext context)
  {
    _unitOfWork = unitOfWork;
    _context = context;
  }


  public IActionResult Index()
  {
    var tags = _unitOfWork.Tag.GetAll();
    return View(tags);
  }

  [HttpGet]
  public IActionResult Create()
  {
    return View();
  }

  [HttpPost]
  public async Task<IActionResult> Create(TagViewModel data)
  {
    if (!ModelState.IsValid) return Json(data);

    var tag = new Tag
    {
      TagName = data.TagName,
      Id = Guid.NewGuid().ToString()
    };

    await _unitOfWork.Tag.Create(tag);
    return RedirectToAction("Index");
  }

  [HttpGet]
  public IActionResult Update(string? id)
  {
    var tag = _unitOfWork.Tag.GetById(id);
    var tagVm = new TagViewModel
    {
      TagName = tag.TagName
    };
    return View(tagVm);
  }

  [HttpPost]
  public async Task<IActionResult> Update(TagViewModel data, string? id)
  {
    if (!ModelState.IsValid) return View(data);

    var tag = _unitOfWork.Tag.GetById(id);
    tag.TagName = data.TagName;
    await _unitOfWork.Tag.Update(tag);
    return RedirectToAction("Index");
  }


  public async Task<IActionResult> Delete(string? id)
  {
    var tag = _unitOfWork.Tag.GetById(id);
    await _unitOfWork.Tag.Delete(tag);
    return RedirectToAction("Index");
  }
  
  [HttpGet]
  [AllowAnonymous]
  public IActionResult AllArticlesForTag(string? tagName)
  {
    var tag = _unitOfWork.Tag.GetAll().FirstOrDefault(t => t.TagName == tagName);
    
    var tagArticles =
      _context.Tags
        .Include(a => a.Articles).ToList()
        .Select(a => a.Articles).ToList();
    
    var tagVm = new TagArticleViewModel
    {
      TagName = tagName,
      TagId = tag?.Id,
      Tag = tag
    };
    return View(tagVm);
  }
}

CSBlog/Controllers/UserController.cs
using System.Diagnostics;
using CSBlog.Core;
using CSBlog.Core.Repository;
using CSBlog.Core.ViewModels.User;
using CSBlog.Models.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CSBlog.Controllers;

public class UserController : Controller
{
  private readonly IUnitOfWork _unitOfWork;
  private readonly SignInManager<BlogUser> _signInManager;

  public UserController(IUnitOfWork unitOfWork, SignInManager<BlogUser> signInManager)
  {
    _unitOfWork = unitOfWork;
    _signInManager = signInManager;
  }

  // GET
  [Authorize(Policy = Constants.Policies.RequireModerator)]
  public IActionResult Index()
  {
    var users = _unitOfWork.User.GetUsers();
    return View(users);
  }

  [HttpGet]
  [Authorize(Policy = Constants.Policies.RequireAdmin)]
  public async Task<IActionResult> Edit(string id)
  {
    var user = _unitOfWork.User.GetUserById(id);

    var roles = _unitOfWork.Role.GetRoles();

    Debug.Assert(user != null, nameof(user) + " != null");
    var userRoles = await _signInManager.UserManager.GetRolesAsync(user);

    var roleListItems = roles.Select(role =>
      new SelectListItem(
        role.Name,
        role.Id,
        userRoles.Any(ur => ur.Contains(role.Name)))).ToList();


    var vm = new EditUserViewModel
    {
      BlogUser = user,
      UserRoles = roleListItems
    };

    return View(vm);
  }

  [HttpPost]
  [Authorize(Policy = Constants.Policies.RequireAdmin)]
  public async Task<IActionResult> Edit(EditUserViewModel data)
  {
    if (!ModelState.IsValid) return View(data);

    var user = _unitOfWork.User.GetUserById(data.BlogUser.Id);
    if (user == null) return NotFound();

    user.FirstName = data.BlogUser.FirstName;
    user.LastName = data.BlogUser.LastName;
    user.Email = data.BlogUser.Email;
    List<string> rolesToAdd = new();
    List<string> rolesToRemove = new();

    var userRoles = await _signInManager.UserManager.GetRolesAsync(user);
    foreach (var role in data.UserRoles)
    {
      if (role.Selected && !userRoles.Contains(role.Text)) rolesToAdd.Add(role.Text);
      if (!role.Selected && userRoles.Contains(role.Text)) rolesToRemove.Add(role.Text);
    }

    if (rolesToAdd.Any()) await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);

    if (rolesToRemove.Any()) await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToRemove);
    user.Updated = DateTime.Now;

    _unitOfWork.User.UpdateUser(user);

    return RedirectToAction("Index");
  }

  [HttpGet]
  [Authorize(Policy = Constants.Policies.RequireAdmin)]
  public IActionResult Delete(BlogUser data)
  {
    var user = _unitOfWork.User.GetUserById(data.Id);

    return View(user);
  }

  [HttpPost]
  [Authorize(Policy = Constants.Policies.RequireAdmin)]
  public async Task<IActionResult> Delete(string id)
  {
    await _unitOfWork.User.DeleteUser(id);

    return RedirectToAction("Index");
  }
}

CSBlog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

@using CSBlog.Models.User
@inject SignInManager<BlogUser> SignInManager
@inject UserManager<BlogUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] - CSBlog</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
  @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.1.0/journal/bootstrap.min.css"> *@
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
  @* <link rel="stylesheet" href="~/CSBlog.styles.css" asp-append-version="true"/> *@
  @* <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script> *@
  <script src="~/lib/tinymice/tinymce.min.js"></script>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
      <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CSBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">

          <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
          </li>
          @* *@
          @* *@
          @* <li class="nav-item"> *@
          @*   <a class="nav-link text-dark" asp-area="" asp-controller="Comment" asp-action="Index">Comments</a> *@
          @* </li> *@
          <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
          </li>
          @* <li class="nav-item"> *@
          @*   <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a> *@
          @* </li> *@
          @* <li class="nav-item"> *@
          @*   <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a> *@
          @* </li> *@
          <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
          </li>
          @if (SignInManager.IsSignedIn(User))
          {
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Role Access Demo
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li class="nav-item">
                  <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                </li>
                <li>
                  <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Moderator">Moderator</a>
                </li>
                <li>
                  <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Admin">Admin</a>
                </li>
              </ul>
            </li>
          }
        </ul>
        <partial name="_LoginPartial"/>
      </div>
    </div>
  </nav>
</header>
<div class="container">
  <main role="main" class="pb-3">
    @RenderBody()
  </main>
</div>


<footer class="bg-light text-center text-lg-start border-top footer text-muted">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Footer text</h5>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
          aliquam voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Footer text</h5>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
          aliquam voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <a class="text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    &copy; 2022 - CSBlog - Copyright:
    <a href="#">CSBlog.site</a>
  </div>
  <!-- Copyright -->
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<partial name="_ValidationScriptsPartial"></partial>
@await RenderSectionAsync("Scripts", false)

</body>
</html>

CSBlog/Views/Shared/_TextEditorPartial.cshtml
<script type="text/javascript">
  tinymce.init({
    selector: '#text-area',
    menu: {
    happy: {title: 'Code', items: 'code'}
    },
    height: 500,
    toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image |  forecolor backcolor emoticons',
    plugins: 'code',  // required by the code menu item
    menubar: 'happy'
  });
  </script>